# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.

# version numbers
jdk:
  - openjdk16

sudo: false

# Отправлять уведомление на почту mail to:youremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - evgeniysanich@mail.ru
    on_success: never # default: change
    on_failure: always # default: always
